# Generated by Django 5.2.5 on 2025-09-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scentpick', '0002_conversation_external_thread_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chat_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
