# Generated by Django 5.2.5 on 2025-09-09 03:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('user', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detail', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('birth_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Detail',
                'verbose_name_plural': 'User Details',
                'db_table': 'users',
                'indexes': [models.Index(fields=['name'], name='users_name_da470e_idx'), models.Index(fields=['gender'], name='users_gender_c12881_idx'), models.Index(fields=['created_at'], name='users_created_6541e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='OAuthAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=40)),
                ('provider_user_id', models.CharField(max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'oauth_accounts',
                'indexes': [models.Index(fields=['provider'], name='oauth_accou_provide_bf96d7_idx'), models.Index(fields=['provider_user_id'], name='oauth_accou_provide_f04777_idx'), models.Index(fields=['user'], name='oauth_accou_user_id_9d8b45_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_user_id'), name='uq_oauth_provider_user'), models.UniqueConstraint(fields=('user', 'provider'), name='uq_oauth_user_provider')],
            },
        ),
    ]
