# Generated by Django 5.2.5 on 2025-09-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='profile_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='OAuthAccount',
        ),
    ]
